# Generated by Django 5.2.9 on 2026-02-01
# Initial migration for selfhealing Django models

from django.contrib.auth.models import Group
from django.db import migrations, models
import uuid


def create_selfhealing_groups(apps, schema_editor):
    """selfhealing RBAC 그룹 생성."""
    groups = [
        "selfhealing_viewer",
        "selfhealing_operator",
        "selfhealing_admin",
        "selfhealing_chaos_tester",
    ]
    for group_name in groups:
        Group.objects.get_or_create(name=group_name)


def remove_selfhealing_groups(apps, schema_editor):
    """selfhealing RBAC 그룹 삭제 (롤백용)."""
    groups = [
        "selfhealing_viewer",
        "selfhealing_operator",
        "selfhealing_admin",
        "selfhealing_chaos_tester",
    ]
    Group.objects.filter(name__in=groups).delete()


class Migration(migrations.Migration):
    """
    Self-Healing 시스템 초기 마이그레이션.

    생성 내용:
    - RBAC 그룹 (viewer, operator, admin, chaos_tester)
    - PostmortemRecord 테이블
    - CascadeEventArchive 테이블
    """

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        # RBAC 그룹 생성
        migrations.RunPython(
            create_selfhealing_groups,
            reverse_code=remove_selfhealing_groups,
        ),
        # PostmortemRecord 테이블
        migrations.CreateModel(
            name="PostmortemRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for the incident",
                        max_length=100,
                        unique=True,
                        verbose_name="Incident ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When the incident started",
                        verbose_name="Incident Start Time",
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When the incident was resolved",
                        null=True,
                        verbose_name="Incident Resolution Time",
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        db_index=True,
                        default=0.0,
                        help_text="Total duration of the incident in seconds",
                        verbose_name="Duration (seconds)",
                    ),
                ),
                (
                    "affected_services",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of services impacted by the incident",
                        verbose_name="Affected Services",
                    ),
                ),
                (
                    "timeline",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Chronological list of events during the incident",
                        verbose_name="Timeline",
                    ),
                ),
                (
                    "auto_actions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of automatic recovery actions performed",
                        verbose_name="Automatic Actions",
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Suggested actions for future prevention",
                        verbose_name="Recommendations",
                    ),
                ),
                (
                    "system_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="System state snapshot at the time of incident",
                        verbose_name="System Snapshot",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Record Created At",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("auto", "Automatic (System Generated)"),
                            ("manual", "Manual (User Created)"),
                        ],
                        db_index=True,
                        default="auto",
                        help_text="How this post-mortem was created (auto/manual)",
                        max_length=20,
                        verbose_name="Source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Postmortem Record",
                "verbose_name_plural": "Postmortem Records",
                "db_table": "selfhealing_postmortem",
                "ordering": ["-started_at"],
            },
        ),
        # PostmortemRecord 인덱스
        migrations.AddIndex(
            model_name="postmortemrecord",
            index=models.Index(
                fields=["-started_at", "-duration_seconds"],
                name="selfhealing_started_db4926_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="postmortemrecord",
            index=models.Index(
                fields=["source", "-created_at"],
                name="selfhealing_source_d92f33_idx",
            ),
        ),
        # CascadeEventArchive 테이블
        migrations.CreateModel(
            name="CascadeEventArchive",
            fields=[
                (
                    "cascade_id",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Cascade ID",
                        help_text="Cascade Event 고유 ID",
                    ),
                ),
                (
                    "namespace",
                    models.CharField(
                        max_length=100,
                        db_index=True,
                        verbose_name="Namespace",
                        help_text="이벤트가 발생한 네임스페이스",
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        max_length=50,
                        db_index=True,
                        verbose_name="Trigger Type",
                        help_text="Cascade를 시작한 트리거 유형",
                    ),
                ),
                (
                    "trigger_details",
                    models.JSONField(
                        default=dict,
                        verbose_name="Trigger Details",
                        help_text="트리거 상세 정보",
                    ),
                ),
                (
                    "effects",
                    models.JSONField(
                        default=list,
                        verbose_name="Effects",
                        help_text="연쇄 효과 목록",
                    ),
                ),
                (
                    "causation_chain",
                    models.JSONField(
                        default=list,
                        verbose_name="Causation Chain",
                        help_text="인과관계 이벤트 ID 체인",
                    ),
                ),
                (
                    "previous_hash",
                    models.CharField(
                        max_length=64,
                        blank=True,
                        default="",
                        verbose_name="Previous Hash",
                        help_text="이전 Cascade Event의 해시",
                    ),
                ),
                (
                    "current_hash",
                    models.CharField(
                        max_length=64,
                        db_index=True,
                        verbose_name="Current Hash",
                        help_text="현재 Cascade Event의 SHA-256 해시",
                    ),
                ),
                (
                    "total_effects",
                    models.PositiveIntegerField(
                        default=0,
                        verbose_name="Total Effects",
                        help_text="총 효과 수",
                    ),
                ),
                (
                    "success_count",
                    models.PositiveIntegerField(
                        default=0,
                        verbose_name="Success Count",
                        help_text="성공한 효과 수",
                    ),
                ),
                (
                    "failure_count",
                    models.PositiveIntegerField(
                        default=0,
                        verbose_name="Failure Count",
                        help_text="실패한 효과 수",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        verbose_name="Event Timestamp",
                        help_text="Cascade Event 발생 시각",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Archived At",
                        help_text="PostgreSQL로 아카이브된 시각",
                    ),
                ),
                (
                    "external_trace",
                    models.JSONField(
                        null=True,
                        blank=True,
                        default=None,
                        verbose_name="External Trace Context",
                        help_text="W3C Trace Context 연동 정보",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        max_length=10,
                        default="1.0",
                        verbose_name="Schema Version",
                        help_text="데이터 스키마 버전",
                    ),
                ),
                (
                    "is_test",
                    models.BooleanField(
                        default=False,
                        db_index=True,
                        verbose_name="Is Test Event",
                        help_text="테스트 환경 이벤트 여부 (X-Test-Mode)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cascade Event Archive",
                "verbose_name_plural": "Cascade Event Archives",
                "db_table": "selfhealing_cascade_events",
                "ordering": ["-timestamp"],
            },
        ),
        # CascadeEventArchive 인덱스
        migrations.AddIndex(
            model_name="cascadeeventarchive",
            index=models.Index(
                fields=["namespace", "-timestamp"],
                name="idx_cascade_ns_ts",
            ),
        ),
        migrations.AddIndex(
            model_name="cascadeeventarchive",
            index=models.Index(
                fields=["trigger_type"],
                name="idx_cascade_trigger",
            ),
        ),
        migrations.AddIndex(
            model_name="cascadeeventarchive",
            index=models.Index(
                fields=["current_hash"],
                name="idx_cascade_hash",
            ),
        ),
        migrations.AddIndex(
            model_name="cascadeeventarchive",
            index=models.Index(
                fields=["is_test", "-timestamp"],
                name="idx_cascade_test_ts",
            ),
        ),
    ]
