# Generated by Django 5.2.9 on 2025-12-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CircuitBreakerState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Service Name",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("closed", "Closed (Normal)"),
                            ("open", "Open (Blocked)"),
                            ("half_open", "Half-Open (Testing)"),
                        ],
                        default="closed",
                        max_length=20,
                        verbose_name="State",
                    ),
                ),
                (
                    "failure_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Failure Count"
                    ),
                ),
                (
                    "success_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Success Count"
                    ),
                ),
                (
                    "last_failure_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Failure At"
                    ),
                ),
                (
                    "last_success_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Success At"
                    ),
                ),
                (
                    "opened_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Opened At"
                    ),
                ),
                (
                    "half_opened_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Half Opened At"
                    ),
                ),
                (
                    "manually_controlled",
                    models.BooleanField(
                        default=False, verbose_name="Manually Controlled"
                    ),
                ),
                (
                    "controlled_by_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Controlled By User ID"
                    ),
                ),
                (
                    "control_reason",
                    models.TextField(blank=True, verbose_name="Control Reason"),
                ),
                (
                    "manual_override_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Manual Override Expires At"
                    ),
                ),
                (
                    "half_open_request_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Half-Open Request Count"
                    ),
                ),
                (
                    "failure_threshold",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Failure Threshold"
                    ),
                ),
                (
                    "recovery_timeout",
                    models.PositiveIntegerField(
                        default=60, verbose_name="Recovery Timeout (seconds)"
                    ),
                ),
                (
                    "half_open_max_calls",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Half-Open Max Calls"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Circuit Breaker State",
                "verbose_name_plural": "Circuit Breaker States",
                "db_table": "selfhealing_circuit_breaker_state",
            },
        ),
        migrations.CreateModel(
            name="FailedOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("payment", "Payment"),
                            ("point", "Point"),
                            ("inventory", "Inventory"),
                            ("webhook", "Webhook"),
                            ("notification", "Notification"),
                        ],
                        db_index=True,
                        help_text="Business domain where the failure occurred",
                        max_length=50,
                        verbose_name="Domain",
                    ),
                ),
                (
                    "failure_type",
                    models.CharField(
                        db_index=True,
                        help_text="Specific failure classification (e.g., PG_TIMEOUT, AMOUNT_MISMATCH)",
                        max_length=100,
                        verbose_name="Failure Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("reviewing", "Under Review"),
                            ("replayed", "Replay Queued"),
                            ("requires_review", "Requires Human Review"),
                            ("resolved", "Resolved"),
                            ("rejected", "Rejected (Unrecoverable)"),
                            ("archived", "Archived"),
                            ("expired", "Retention Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="Order ID"
                    ),
                ),
                (
                    "payment_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="Payment ID"
                    ),
                ),
                (
                    "user_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="User ID"
                    ),
                ),
                (
                    "snapshot_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Complete state snapshot for recovery",
                        verbose_name="Snapshot Data",
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Error Code"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Error Message"),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(default=0, verbose_name="Retry Count"),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(default=3, verbose_name="Max Retries"),
                ),
                (
                    "last_retry_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Retry At"
                    ),
                ),
                (
                    "next_retry_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Next Retry At"
                    ),
                ),
                (
                    "request_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Request Data"
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Response Data"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolved At"
                    ),
                ),
                (
                    "resolved_by_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Resolved By User ID"
                    ),
                ),
                (
                    "resolution_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("auto_replay", "Automatic Replay"),
                            ("manual_fix", "Manual Fix"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("internal_error", "Internal Error"),
                            ("archived", "Archived"),
                        ],
                        max_length=30,
                        verbose_name="Resolution Type",
                    ),
                ),
                (
                    "resolution_note",
                    models.TextField(blank=True, verbose_name="Resolution Note"),
                ),
                (
                    "next_action_hint",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Next Action Hint"
                    ),
                ),
                (
                    "recommended_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("replay", "Replay Operation"),
                            ("manual_check", "Manual Verification"),
                            ("escalate", "Escalate to Senior"),
                            ("archive", "Archive (No Action)"),
                        ],
                        max_length=30,
                        verbose_name="Recommended Action",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expires At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Failed Operation",
                "verbose_name_plural": "Failed Operations",
                "db_table": "selfhealing_failed_operation",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["domain", "status"],
                        name="selfhealing_domain_41688f_idx",
                    ),
                    models.Index(
                        fields=["failure_type", "status"],
                        name="selfhealing_failure_7420bc_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="selfhealing_status_68cf46_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="selfhealing_expires_5f8d45_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("webhook_signature_invalid", "Webhook Signature Invalid"),
                            ("payment_amount_tampered", "Payment Amount Tampered"),
                            ("token_forged", "Token Forged"),
                            ("unauthorized_access", "Unauthorized Access"),
                            ("rate_limit_abuse", "Rate Limit Abuse"),
                            ("suspicious_activity", "Suspicious Activity"),
                            ("replay_attack", "Replay Attack Detected"),
                            ("injection_attempt", "Injection Attempt"),
                        ],
                        db_index=True,
                        max_length=100,
                        verbose_name="Incident Type",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Severity",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("investigating", "Investigating"),
                            ("resolved", "Resolved"),
                            ("false_positive", "False Positive"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "source_ip",
                    models.GenericIPAddressField(
                        blank=True, db_index=True, null=True, verbose_name="Source IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "user_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="User ID"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "context",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Context Data"
                    ),
                ),
                (
                    "raw_request",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Raw Request"
                    ),
                ),
                (
                    "action_taken",
                    models.TextField(blank=True, verbose_name="Action Taken"),
                ),
                (
                    "investigated_by_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Investigated By User ID"
                    ),
                ),
                (
                    "investigation_notes",
                    models.TextField(blank=True, verbose_name="Investigation Notes"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolved At"
                    ),
                ),
                (
                    "order_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Order ID"
                    ),
                ),
                (
                    "payment_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Payment ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Security Incident",
                "verbose_name_plural": "Security Incidents",
                "db_table": "selfhealing_security_incident",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["incident_type", "status"],
                        name="selfhealing_inciden_b1d7ee_idx",
                    ),
                    models.Index(
                        fields=["severity", "status"],
                        name="selfhealing_severit_d2785e_idx",
                    ),
                    models.Index(
                        fields=["source_ip", "-created_at"],
                        name="selfhealing_source__51d6c7_idx",
                    ),
                ],
            },
        ),
    ]
