# Generated by Django 5.2.9 on 2025-12-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selfhealing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="failedoperation",
            name="order_id",
        ),
        migrations.RemoveField(
            model_name="failedoperation",
            name="payment_id",
        ),
        migrations.RemoveField(
            model_name="securityincident",
            name="order_id",
        ),
        migrations.RemoveField(
            model_name="securityincident",
            name="payment_id",
        ),
        migrations.AddField(
            model_name="failedoperation",
            name="entity_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID of the related entity",
                max_length=100,
                verbose_name="Entity ID",
            ),
        ),
        migrations.AddField(
            model_name="failedoperation",
            name="entity_refs",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional entity references (e.g., {'user_id': 123, 'tenant_id': 'abc'})",
                verbose_name="Entity References",
            ),
        ),
        migrations.AddField(
            model_name="failedoperation",
            name="entity_type",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Type of related entity (e.g., 'order', 'subscription', 'user')",
                max_length=100,
                verbose_name="Entity Type",
            ),
        ),
        migrations.AddField(
            model_name="securityincident",
            name="entity_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, verbose_name="Entity ID"
            ),
        ),
        migrations.AddField(
            model_name="securityincident",
            name="entity_refs",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional entity references as key-value pairs",
                verbose_name="Entity References",
            ),
        ),
        migrations.AddField(
            model_name="securityincident",
            name="entity_type",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Type of related entity (e.g., 'order', 'subscription')",
                max_length=100,
                verbose_name="Entity Type",
            ),
        ),
        migrations.AlterField(
            model_name="securityincident",
            name="incident_type",
            field=models.CharField(
                choices=[
                    ("signature_invalid", "Signature Invalid"),
                    ("data_tampered", "Data Tampered"),
                    ("token_forged", "Token Forged"),
                    ("unauthorized_access", "Unauthorized Access"),
                    ("rate_limit_abuse", "Rate Limit Abuse"),
                    ("suspicious_activity", "Suspicious Activity"),
                    ("replay_attack", "Replay Attack Detected"),
                    ("injection_attempt", "Injection Attempt"),
                    ("webhook_signature_invalid", "Webhook Signature Invalid"),
                    ("amount_tampered", "Amount Tampered"),
                ],
                db_index=True,
                max_length=100,
                verbose_name="Incident Type",
            ),
        ),
    ]
