# Generated by Django 5.2.4 on 2025-12-01 01:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0014_notification_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "store_name",
                    models.CharField(help_text="고객에게 표시되는 스토어 이름", max_length=100, verbose_name="스토어명"),
                ),
                (
                    "store_description",
                    models.TextField(blank=True, help_text="스토어에 대한 간단한 소개글", verbose_name="스토어 소개"),
                ),
                (
                    "business_number",
                    models.CharField(
                        help_text="'-' 없이 10자리 숫자 (예: 1234567890)",
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="사업자등록번호는 10자리 숫자여야 합니다.", regex="^\\d{10}$"
                            )
                        ],
                        verbose_name="사업자등록번호",
                    ),
                ),
                ("representative_name", models.CharField(max_length=50, verbose_name="대표자명")),
                ("business_address", models.CharField(blank=True, max_length=200, verbose_name="사업장 주소")),
                (
                    "bank_name",
                    models.CharField(help_text="정산받을 은행 (예: 국민은행, 신한은행)", max_length=20, verbose_name="은행명"),
                ),
                ("bank_account", models.CharField(help_text="'-' 없이 숫자만 입력", max_length=30, verbose_name="계좌번호")),
                ("bank_holder", models.CharField(max_length=50, verbose_name="예금주")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="등록일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "판매자 프로필",
                "verbose_name_plural": "판매자 프로필",
            },
        ),
    ]
