# Generated by Django 5.2.4 on 2025-12-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0016_add_stock_check_constraint"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="product",
            name="product_stock_non_negative",
        ),
        migrations.RemoveConstraint(
            model_name="product",
            name="product_sold_count_non_negative",
        ),
    ]
