# Generated by Django 5.2.4 on 2025-12-02
# Migration for adding idempotency_key to Payment model

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0017_remove_product_product_stock_non_negative_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="결제 요청의 멱등성을 보장하기 위한 고유 키 (클라이언트가 생성)",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="멱등성 키",
            ),
        ),
    ]
