# Generated by Django 5.2.4 on 2025-12-02 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0019_webhookevent_remove_idempotency_unique"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="webhookevent",
            new_name="shopping_we_source_fa6bc6_idx",
            old_name="shopping_we_source_f4c8e3_idx",
        ),
        migrations.RenameIndex(
            model_name="webhookevent",
            new_name="shopping_we_process_096a70_idx",
            old_name="shopping_we_process_c5b9e1_idx",
        ),
    ]
