# Generated by Django 5.2.4 on 2025-12-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0020_rename_shopping_we_source_f4c8e3_idx_shopping_we_source_fa6bc6_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="price_at_add",
            field=models.DecimalField(
                decimal_places=0,
                help_text="장바구니에 담을 때의 상품 가격",
                max_digits=10,
                null=True,
                verbose_name="담은 시점 가격",
            ),
        ),
    ]
