# Generated by Django 5.2.4 on 2025-12-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0021_cartitem_price_at_add"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="earn_rate_at_order",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="주문 생성 시점의 회원 등급별 적립률 (%)", verbose_name="주문 시점 적립률"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="membership_at_order",
            field=models.CharField(
                blank=True,
                default="",
                help_text="주문 생성 시점의 회원 등급",
                max_length=10,
                verbose_name="주문 시점 회원등급",
            ),
        ),
    ]
