# Generated by Django 5.2.9 on 2025-12-07 17:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0022_order_earn_rate_at_order_order_membership_at_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "결제대기"),
                    ("confirmed", "주문확정"),
                    ("paid", "결제완료"),
                    ("preparing", "배송준비중"),
                    ("shipped", "배송중"),
                    ("delivered", "배송완료"),
                    ("canceled", "주문취소"),
                    ("refunded", "환불완료"),
                    ("payment_failed", "결제실패"),
                    ("failed", "주문실패"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="주문상태",
            ),
        ),
        migrations.AlterField(
            model_name="pointhistory",
            name="type",
            field=models.CharField(
                choices=[
                    ("earn", "적립"),
                    ("use", "사용"),
                    ("cancel_refund", "취소환불"),
                    ("cancel_deduct", "취소차감"),
                    ("payment_fail_refund", "결제실패환불"),
                    ("expire", "만료"),
                    ("admin_add", "관리자지급"),
                    ("admin_deduct", "관리자차감"),
                    ("event", "이벤트"),
                ],
                max_length=20,
                verbose_name="타입",
            ),
        ),
        migrations.CreateModel(
            name="CircuitBreakerState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("service_name", models.CharField(max_length=50, unique=True, verbose_name="서비스명")),
                (
                    "state",
                    models.CharField(
                        choices=[("closed", "정상 (Closed)"), ("open", "차단 (Open)"), ("half_open", "테스트 중 (Half-Open)")],
                        default="closed",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("failure_count", models.PositiveIntegerField(default=0, verbose_name="연속 실패 횟수")),
                ("success_count", models.PositiveIntegerField(default=0, verbose_name="성공 횟수 (Half-Open)")),
                ("last_failure_at", models.DateTimeField(blank=True, null=True, verbose_name="마지막 실패 시각")),
                ("opened_at", models.DateTimeField(blank=True, null=True, verbose_name="Open 전환 시각")),
                (
                    "manually_controlled",
                    models.BooleanField(
                        default=False, help_text="운영자가 수동으로 상태를 변경한 경우 True", verbose_name="수동 제어 여부"
                    ),
                ),
                ("control_reason", models.TextField(blank=True, verbose_name="제어 사유")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "controlled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="circuit_breaker_controls",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="제어자",
                    ),
                ),
            ],
            options={
                "verbose_name": "Circuit Breaker 상태",
                "verbose_name_plural": "Circuit Breaker 상태 목록",
                "db_table": "shopping_circuit_breaker_state",
            },
        ),
        migrations.CreateModel(
            name="FailedPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payment_key", models.CharField(blank=True, max_length=200, verbose_name="토스 결제키")),
                ("toss_order_id", models.CharField(blank=True, max_length=100, verbose_name="토스 주문번호")),
                (
                    "amount",
                    models.DecimalField(decimal_places=0, default=Decimal("0"), max_digits=10, verbose_name="결제 금액"),
                ),
                (
                    "failure_type",
                    models.CharField(
                        choices=[
                            ("max_retries_exceeded", "최대 재시도 횟수 초과"),
                            ("non_retryable_error", "재시도 불가능한 오류"),
                            ("sla_timeout", "SLA 타임아웃 초과"),
                            ("circuit_breaker_open", "Circuit Breaker 차단"),
                            ("manual_abort", "수동 중단"),
                            ("unknown", "알 수 없는 오류"),
                        ],
                        default="unknown",
                        max_length=30,
                        verbose_name="실패 유형",
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=100, verbose_name="에러 코드")),
                ("error_message", models.TextField(blank=True, verbose_name="에러 메시지")),
                ("retry_count", models.PositiveIntegerField(default=0, verbose_name="재시도 횟수")),
                ("last_retry_at", models.DateTimeField(blank=True, null=True, verbose_name="마지막 재시도 시각")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "검토 대기"),
                            ("reviewing", "검토 중"),
                            ("resolved", "해결됨"),
                            ("rejected", "복구 불가"),
                            ("expired", "보관 기간 만료"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="처리 상태",
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True, verbose_name="해결 시각")),
                ("resolution_note", models.TextField(blank=True, verbose_name="해결 메모")),
                ("request_data", models.JSONField(blank=True, default=dict, verbose_name="요청 데이터")),
                ("response_data", models.JSONField(blank=True, default=dict, verbose_name="응답 데이터")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="메타데이터")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("expires_at", models.DateTimeField(blank=True, null=True, verbose_name="보관 만료일")),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="failed_payment_records",
                        to="shopping.order",
                        verbose_name="주문",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="failed_records",
                        to="shopping.payment",
                        verbose_name="원본 결제",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_failed_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="해결자",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="failed_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "실패 결제 (DLQ)",
                "verbose_name_plural": "실패 결제 목록 (DLQ)",
                "db_table": "shopping_failed_payment",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "-created_at"], name="shopping_fa_status_b740f4_idx"),
                    models.Index(fields=["failure_type", "-created_at"], name="shopping_fa_failure_ad7a2a_idx"),
                    models.Index(fields=["expires_at"], name="shopping_fa_expires_6e0deb_idx"),
                    models.Index(fields=["-created_at"], name="shopping_fa_created_adba8f_idx"),
                ],
            },
        ),
    ]
