# Generated by Django 5.2.9 on 2025-12-08 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0023_add_failed_payment_and_circuit_breaker"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailedOperation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("payment", "Payment"),
                            ("point", "Point"),
                            ("inventory", "Inventory"),
                            ("webhook", "Webhook"),
                            ("notification", "Notification"),
                        ],
                        db_index=True,
                        help_text="Business domain where the failure occurred",
                        max_length=50,
                        verbose_name="Domain",
                    ),
                ),
                (
                    "failure_type",
                    models.CharField(
                        db_index=True,
                        help_text="Specific failure classification (e.g., PG_TIMEOUT, AMOUNT_MISMATCH)",
                        max_length=100,
                        verbose_name="Failure Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("reviewing", "Under Review"),
                            ("replayed", "Replay Queued"),
                            ("resolved", "Resolved"),
                            ("rejected", "Rejected (Unrecoverable)"),
                            ("expired", "Retention Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "snapshot_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Complete state snapshot for recovery without accessing original records",
                        verbose_name="Snapshot Data",
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=100, verbose_name="Error Code")),
                ("error_message", models.TextField(blank=True, verbose_name="Error Message")),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of replay attempts from DLQ", verbose_name="Retry Count"
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(
                        default=2, help_text="Maximum allowed replay attempts (default: 2)", verbose_name="Max Retries"
                    ),
                ),
                ("last_retry_at", models.DateTimeField(blank=True, null=True, verbose_name="Last Retry At")),
                (
                    "request_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Original request payload", verbose_name="Request Data"
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="External system response", verbose_name="Response Data"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional debug info: timing, retry history, state snapshots",
                        verbose_name="Metadata",
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True, verbose_name="Resolved At")),
                (
                    "resolution_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("auto_replay", "Automatic Replay"),
                            ("manual_fix", "Manual Fix"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        max_length=30,
                        verbose_name="Resolution Type",
                    ),
                ),
                ("resolution_note", models.TextField(blank=True, verbose_name="Resolution Note")),
                (
                    "next_action_hint",
                    models.CharField(
                        blank=True,
                        help_text="Guidance for operators (e.g., 'Verify payment in PG admin')",
                        max_length=200,
                        verbose_name="Next Action Hint",
                    ),
                ),
                (
                    "recommended_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("replay", "Replay Operation"),
                            ("manual_check", "Manual Verification"),
                            ("escalate", "Escalate to Senior"),
                            ("archive", "Archive (No Action)"),
                        ],
                        max_length=30,
                        verbose_name="Recommended Action",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Auto-archive after retention period",
                        null=True,
                        verbose_name="Expires At",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="failed_operations",
                        to="shopping.order",
                        verbose_name="Order",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="failed_operations",
                        to="shopping.payment",
                        verbose_name="Payment",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_operations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Resolved By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="failed_operations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Failed Operation (DLQ)",
                "verbose_name_plural": "Failed Operations (DLQ)",
                "db_table": "failed_operations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["domain", "status"], name="failed_oper_domain_d5354d_idx"),
                    models.Index(fields=["failure_type", "status"], name="failed_oper_failure_ac8fc9_idx"),
                    models.Index(fields=["status", "-created_at"], name="failed_oper_status_f7917d_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityIncident",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("webhook_signature_invalid", "Webhook Signature Invalid"),
                            ("payment_amount_tampered", "Payment Amount Tampered"),
                            ("token_forged", "Token Forged"),
                            ("unauthorized_access", "Unauthorized Access"),
                            ("rate_limit_abuse", "Rate Limit Abuse"),
                            ("suspicious_activity", "Suspicious Activity"),
                            ("replay_attack", "Replay Attack Detected"),
                            ("injection_attempt", "Injection Attempt"),
                        ],
                        db_index=True,
                        max_length=100,
                        verbose_name="Incident Type",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("critical", "Critical"), ("high", "High"), ("medium", "Medium")],
                        db_index=True,
                        max_length=20,
                        verbose_name="Severity",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("investigating", "Investigating"),
                            ("resolved", "Resolved"),
                            ("false_positive", "False Positive"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "source_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        db_index=True,
                        help_text="IP address of the request origin",
                        null=True,
                        verbose_name="Source IP",
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the security incident", verbose_name="Description"),
                ),
                (
                    "raw_request",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Sanitized request data for forensic analysis",
                        verbose_name="Raw Request",
                    ),
                ),
                (
                    "action_taken",
                    models.TextField(
                        blank=True,
                        help_text="Immediate protective action taken (e.g., 'Session invalidated')",
                        verbose_name="Action Taken",
                    ),
                ),
                ("investigation_notes", models.TextField(blank=True, verbose_name="Investigation Notes")),
                ("resolved_at", models.DateTimeField(blank=True, null=True, verbose_name="Resolved At")),
                ("detected_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Detected At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "investigated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_investigations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Investigated By",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_incidents",
                        to="shopping.order",
                        verbose_name="Related Order",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_incidents",
                        to="shopping.payment",
                        verbose_name="Related Payment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User associated with the incident (if authenticated)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_incidents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Associated User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Incident",
                "verbose_name_plural": "Security Incidents",
                "db_table": "security_incidents",
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(fields=["incident_type", "status"], name="security_in_inciden_a4746d_idx"),
                    models.Index(fields=["severity", "status"], name="security_in_severit_11fcd0_idx"),
                    models.Index(fields=["source_ip", "-detected_at"], name="security_in_source__2b8a86_idx"),
                    models.Index(fields=["status", "-detected_at"], name="security_in_status_7da6f8_idx"),
                ],
            },
        ),
    ]
