# Generated by Django 5.2.9 on 2025-12-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0024_add_failed_operation_and_security_incident"),
    ]

    operations = [
        migrations.AddField(
            model_name="circuitbreakerstate",
            name="half_open_request_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of requests allowed through in half-open state",
                verbose_name="Half-Open 요청 횟수",
            ),
        ),
        migrations.AddField(
            model_name="circuitbreakerstate",
            name="manual_override_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Manual override automatically expires after this time",
                null=True,
                verbose_name="수동 제어 만료 시각",
            ),
        ),
        migrations.AlterField(
            model_name="failedoperation",
            name="resolution_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("auto_replay", "Automatic Replay"),
                    ("manual_fix", "Manual Fix"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                    ("internal_error", "Internal Error"),
                    ("archived", "Archived"),
                ],
                max_length=30,
                verbose_name="Resolution Type",
            ),
        ),
        migrations.AlterField(
            model_name="failedoperation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("reviewing", "Under Review"),
                    ("replayed", "Replay Queued"),
                    ("requires_review", "Requires Human Review"),
                    ("resolved", "Resolved"),
                    ("rejected", "Rejected (Unrecoverable)"),
                    ("archived", "Archived"),
                    ("expired", "Retention Expired"),
                ],
                db_index=True,
                default="pending",
                max_length=30,
                verbose_name="Status",
            ),
        ),
    ]
