# Generated by Django 5.2.9 on 2025-12-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0025_circuit_breaker_ttl"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateLimitState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "key",
                    models.CharField(
                        db_index=True, help_text="Unique identifier for the rate-limited resource", max_length=255, unique=True
                    ),
                ),
                ("cooldown_until", models.FloatField(default=0.0, help_text="Unix timestamp when cooldown period ends")),
                (
                    "consecutive_429s",
                    models.IntegerField(default=0, help_text="Number of consecutive 429 responses for backoff calculation"),
                ),
                ("last_updated", models.FloatField(default=0.0, help_text="Unix timestamp of last state update")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rate Limit State",
                "verbose_name_plural": "Rate Limit States",
                "db_table": "selfhealing_ratelimitstate",
                "indexes": [models.Index(fields=["key"], name="idx_ratelimit_key")],
            },
        ),
    ]
