# Generated by Django 5.2.9 on 2025-12-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0026_rate_limit_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="failedoperation",
            name="order",
        ),
        migrations.RemoveField(
            model_name="failedoperation",
            name="payment",
        ),
        migrations.AddField(
            model_name="failedoperation",
            name="entity_id",
            field=models.CharField(
                blank=True, db_index=True, help_text="ID of related entity", max_length=100, verbose_name="Entity ID"
            ),
        ),
        migrations.AddField(
            model_name="failedoperation",
            name="entity_type",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Type of related entity (e.g., 'order', 'payment', 'subscription')",
                max_length=100,
                verbose_name="Entity Type",
            ),
        ),
    ]
