# Generated by Django 5.2.9 on 2025-12-25 16:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0028_rename_failedpayment_to_failedexternalrequest"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="failedexternalrequest",
            new_name="shopping_fa_status_293e29_idx",
            old_name="shopping_fa_status_b740f4_idx",
        ),
        migrations.RenameIndex(
            model_name="failedexternalrequest",
            new_name="shopping_fa_failure_15c6e3_idx",
            old_name="shopping_fa_failure_ad7a2a_idx",
        ),
        migrations.RenameIndex(
            model_name="failedexternalrequest",
            new_name="shopping_fa_domain_b3c13c_idx",
            old_name="shopping_fa_domain_abc123_idx",
        ),
        migrations.RenameIndex(
            model_name="failedexternalrequest",
            new_name="shopping_fa_expires_7cf79a_idx",
            old_name="shopping_fa_expires_6e0deb_idx",
        ),
        migrations.RenameIndex(
            model_name="failedexternalrequest",
            new_name="shopping_fa_created_2d0006_idx",
            old_name="shopping_fa_created_adba8f_idx",
        ),
        migrations.RemoveField(
            model_name="circuitbreakerstate",
            name="controlled_by",
        ),
        migrations.RemoveField(
            model_name="failedexternalrequest",
            name="external_order_id",
        ),
        migrations.RemoveField(
            model_name="failedexternalrequest",
            name="order",
        ),
        migrations.RemoveField(
            model_name="failedexternalrequest",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="failedexternalrequest",
            name="resolved_by",
        ),
        migrations.RemoveField(
            model_name="failedexternalrequest",
            name="user",
        ),
        migrations.AddField(
            model_name="circuitbreakerstate",
            name="controlled_by_id",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="제어자 ID"),
        ),
        migrations.AddField(
            model_name="failedexternalrequest",
            name="entity_id",
            field=models.CharField(
                blank=True, db_index=True, help_text="관련 엔티티의 ID", max_length=100, verbose_name="엔티티 ID"
            ),
        ),
        migrations.AddField(
            model_name="failedexternalrequest",
            name="entity_refs",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="추가 엔티티 참조 (예: {'user_id': 123, 'tenant_id': 'abc'})",
                verbose_name="엔티티 참조",
            ),
        ),
        migrations.AddField(
            model_name="failedexternalrequest",
            name="entity_type",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="관련 엔티티 타입 (예: 'order', 'payment', 'subscription')",
                max_length=100,
                verbose_name="엔티티 타입",
            ),
        ),
        migrations.AddField(
            model_name="failedexternalrequest",
            name="external_transaction_id",
            field=models.CharField(blank=True, max_length=100, verbose_name="외부 트랜잭션 ID"),
        ),
        migrations.AddField(
            model_name="failedexternalrequest",
            name="resolved_by_id",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="해결자 ID"),
        ),
        migrations.AddField(
            model_name="failedexternalrequest",
            name="user_id",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name="사용자 ID"),
        ),
        migrations.AlterField(
            model_name="failedexternalrequest",
            name="amount",
            field=models.DecimalField(decimal_places=0, default=Decimal("0"), max_digits=10, verbose_name="금액"),
        ),
        migrations.AlterField(
            model_name="failedexternalrequest",
            name="domain",
            field=models.CharField(
                choices=[
                    ("external_api", "외부 API"),
                    ("payment", "결제"),
                    ("point", "포인트"),
                    ("inventory", "재고"),
                    ("webhook", "웹훅"),
                    ("notification", "알림"),
                ],
                default="external_api",
                max_length=50,
                verbose_name="도메인",
            ),
        ),
        migrations.AlterField(
            model_name="failedexternalrequest",
            name="external_request_id",
            field=models.CharField(blank=True, max_length=200, verbose_name="외부 요청 ID"),
        ),
        migrations.AddIndex(
            model_name="failedexternalrequest",
            index=models.Index(fields=["entity_type", "entity_id"], name="shopping_fa_entity__d19598_idx"),
        ),
    ]
