# Generated by Django for 136_EXCEPTION_HANDLER_6_ENHANCEMENTS.md Q3 보완

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    AuditLog 모델 마이그레이션.

    Q3 보완: WAL 복구 시 중복 삽입 방지 (2차 방어)
    - audit_event_id: Unique 제약 (ON CONFLICT DO NOTHING 지원)
    - 해시 체인 필드: integrity_hash, previous_hash
    - RBAC: actor_roles
    """

    dependencies = [
        ("shopping", "0029_fix_controlled_by_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                # Unique Event Identifier
                (
                    "audit_event_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for audit event. Used for WAL recovery deduplication.",
                        max_length=128,
                        unique=True,
                        verbose_name="Audit Event ID",
                    ),
                ),
                # Action & Timestamp
                (
                    "action",
                    models.CharField(
                        db_index=True,
                        help_text="Audit action type",
                        max_length=100,
                        verbose_name="Action",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When the action occurred",
                        verbose_name="Timestamp",
                    ),
                ),
                # Actor Information
                (
                    "actor_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Who performed the action",
                        max_length=255,
                        verbose_name="Actor ID",
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Type of actor (user, system, etc.)",
                        max_length=50,
                        verbose_name="Actor Type",
                    ),
                ),
                (
                    "actor_roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="RBAC roles of the actor at action time",
                        verbose_name="Actor Roles",
                    ),
                ),
                # Target Information
                (
                    "target_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Type of target entity",
                        max_length=100,
                        verbose_name="Target Type",
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="ID of target entity",
                        max_length=255,
                        verbose_name="Target ID",
                    ),
                ),
                # Service & Domain
                (
                    "service_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Service that generated the audit event",
                        max_length=100,
                        verbose_name="Service Name",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Business domain",
                        max_length=100,
                        verbose_name="Domain",
                    ),
                ),
                # Details & Reason
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Reason for the action",
                        verbose_name="Reason",
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full action details as JSON",
                        verbose_name="Details",
                    ),
                ),
                # Result
                (
                    "success",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether the action succeeded",
                        verbose_name="Success",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if action failed",
                        verbose_name="Error Message",
                    ),
                ),
                # Integrity (Hash Chain)
                (
                    "integrity_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Hash for integrity verification",
                        max_length=128,
                        verbose_name="Integrity Hash",
                    ),
                ),
                (
                    "previous_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hash of previous entry",
                        max_length=128,
                        verbose_name="Previous Hash",
                    ),
                ),
                (
                    "sequence_number",
                    models.BigIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Monotonic sequence for ordering",
                        verbose_name="Sequence Number",
                    ),
                ),
                # Metadata
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Created At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_log",
                "ordering": ["-sequence_number", "-timestamp"],
            },
        ),
        # Indexes
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "timestamp"],
                name="idx_auditlog_action_ts",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["actor_id", "timestamp"],
                name="idx_auditlog_actor_ts",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["target_type", "target_id"],
                name="idx_auditlog_target",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["service_name", "action"],
                name="idx_auditlog_svc_action",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["success", "timestamp"],
                name="idx_auditlog_success_ts",
            ),
        ),
    ]
