# Generated by Django 5.2.9 on 2026-01-28 09:39
# AuditLog 인덱스 이름 정규화

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    AuditLog 인덱스 이름 변경 (Django 자동 생성 형식으로).
    """

    dependencies = [
        ("shopping", "0030_auditlog"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_log_action_09d227_idx",
            old_name="idx_auditlog_action_ts",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_log_actor_i_e00306_idx",
            old_name="idx_auditlog_actor_ts",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_log_target__0238a6_idx",
            old_name="idx_auditlog_target",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_log_service_098c1b_idx",
            old_name="idx_auditlog_svc_action",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_log_success_e4fe21_idx",
            old_name="idx_auditlog_success_ts",
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                db_index=True,
                help_text="Audit action type (e.g., AUTO_TUNING_ADJUSTMENT, CB_FORCE_OPEN)",
                max_length=100,
                verbose_name="Action",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="actor_id",
            field=models.CharField(
                blank=True, db_index=True, help_text="Who performed the action", max_length=255, verbose_name="Actor ID"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="actor_type",
            field=models.CharField(
                blank=True, help_text="Type of actor (user, system, etc.)", max_length=50, verbose_name="Actor Type"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="audit_event_id",
            field=models.CharField(
                db_index=True,
                help_text="Unique identifier for audit event. Used for WAL recovery deduplication (ON CONFLICT DO NOTHING).",
                max_length=128,
                unique=True,
                verbose_name="Audit Event ID",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="domain",
            field=models.CharField(
                blank=True, db_index=True, help_text="Business domain", max_length=100, verbose_name="Domain"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="error_message",
            field=models.TextField(blank=True, help_text="Error message if action failed", verbose_name="Error Message"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="integrity_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hash for integrity verification (hash chain)",
                max_length=128,
                verbose_name="Integrity Hash",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="previous_hash",
            field=models.CharField(
                blank=True,
                help_text="Hash of previous entry (for chain verification)",
                max_length=128,
                verbose_name="Previous Hash",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="reason",
            field=models.TextField(blank=True, help_text="Reason for the action", verbose_name="Reason"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="service_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Service that generated the audit event",
                max_length=100,
                verbose_name="Service Name",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="target_id",
            field=models.CharField(
                blank=True, db_index=True, help_text="ID of target entity", max_length=255, verbose_name="Target ID"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="target_type",
            field=models.CharField(
                blank=True, db_index=True, help_text="Type of target entity", max_length=100, verbose_name="Target Type"
            ),
        ),
    ]
