# Generated by Django 5.2.9 on 2026-01-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0031_add_selfhealing_chaos_tester_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostmortemRecord",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "incident_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for the incident",
                        max_length=100,
                        unique=True,
                        verbose_name="Incident ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True, help_text="When the incident started", verbose_name="Incident Start Time"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When the incident was resolved",
                        null=True,
                        verbose_name="Incident Resolution Time",
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        db_index=True,
                        default=0.0,
                        help_text="Total duration of the incident in seconds",
                        verbose_name="Duration (seconds)",
                    ),
                ),
                (
                    "affected_services",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of services impacted by the incident",
                        verbose_name="Affected Services",
                    ),
                ),
                (
                    "timeline",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Chronological list of events during the incident",
                        verbose_name="Timeline",
                    ),
                ),
                (
                    "auto_actions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of automatic recovery actions performed",
                        verbose_name="Automatic Actions",
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Suggested actions for future prevention",
                        verbose_name="Recommendations",
                    ),
                ),
                (
                    "system_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="System state snapshot at the time of incident",
                        verbose_name="System Snapshot",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Record Created At")),
                (
                    "source",
                    models.CharField(
                        choices=[("auto", "Automatic (System Generated)"), ("manual", "Manual (User Created)")],
                        db_index=True,
                        default="auto",
                        help_text="How this post-mortem was created (auto/manual)",
                        max_length=20,
                        verbose_name="Source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Postmortem Record",
                "verbose_name_plural": "Postmortem Records",
                "db_table": "selfhealing_postmortem",
                "ordering": ["-started_at"],
                "abstract": False,
            },
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_log_action_09d227_idx",
            old_name="idx_auditlog_action_ts",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_log_actor_i_e00306_idx",
            old_name="idx_auditlog_actor_ts",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_log_target__0238a6_idx",
            old_name="idx_auditlog_target",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_log_service_098c1b_idx",
            old_name="idx_auditlog_svc_action",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_log_success_e4fe21_idx",
            old_name="idx_auditlog_success_ts",
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                db_index=True,
                help_text="Audit action type (e.g., AUTO_TUNING_ADJUSTMENT, CB_FORCE_OPEN)",
                max_length=100,
                verbose_name="Action",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="actor_id",
            field=models.CharField(
                blank=True, db_index=True, help_text="Who performed the action", max_length=255, verbose_name="Actor ID"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="actor_type",
            field=models.CharField(
                blank=True, help_text="Type of actor (user, system, etc.)", max_length=50, verbose_name="Actor Type"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="audit_event_id",
            field=models.CharField(
                db_index=True,
                help_text="Unique identifier for audit event. Used for WAL recovery deduplication (ON CONFLICT DO NOTHING).",
                max_length=128,
                unique=True,
                verbose_name="Audit Event ID",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="domain",
            field=models.CharField(
                blank=True, db_index=True, help_text="Business domain", max_length=100, verbose_name="Domain"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="error_message",
            field=models.TextField(blank=True, help_text="Error message if action failed", verbose_name="Error Message"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="integrity_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hash for integrity verification (hash chain)",
                max_length=128,
                verbose_name="Integrity Hash",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="previous_hash",
            field=models.CharField(
                blank=True,
                help_text="Hash of previous entry (for chain verification)",
                max_length=128,
                verbose_name="Previous Hash",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="reason",
            field=models.TextField(blank=True, help_text="Reason for the action", verbose_name="Reason"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="service_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Service that generated the audit event",
                max_length=100,
                verbose_name="Service Name",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="target_id",
            field=models.CharField(
                blank=True, db_index=True, help_text="ID of target entity", max_length=255, verbose_name="Target ID"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="target_type",
            field=models.CharField(
                blank=True, db_index=True, help_text="Type of target entity", max_length=100, verbose_name="Target Type"
            ),
        ),
        migrations.AddIndex(
            model_name="postmortemrecord",
            index=models.Index(fields=["-started_at", "-duration_seconds"], name="selfhealing_started_db4926_idx"),
        ),
        migrations.AddIndex(
            model_name="postmortemrecord",
            index=models.Index(fields=["source", "-created_at"], name="selfhealing_source_d92f33_idx"),
        ),
    ]
