# Generated by Django migration
# 레거시 모델 삭제 - Redis 기반 selfhealing으로 전환 완료

from django.db import migrations


class Migration(migrations.Migration):
    """
    레거시 Django 모델 삭제.

    - CircuitBreakerState: Redis CircuitBreakerStateRepository로 대체
    - RateLimitState: Redis RateLimitRepository로 대체
    - AuditLog: FileAuditLogAdapter (logs/audit.jsonl)로 대체

    참고: 06_REDIS_MIGRATION.md, 07_HYBRID_STORAGE_ARCHITECTURE.md
    """

    dependencies = [
        ("shopping", "0031_auditlog_index_rename"),
    ]

    operations = [
        # CircuitBreakerState 테이블 삭제
        migrations.DeleteModel(
            name="CircuitBreakerState",
        ),
        # RateLimitState 테이블 삭제
        migrations.DeleteModel(
            name="RateLimitState",
        ),
        # AuditLog 테이블 삭제
        migrations.DeleteModel(
            name="AuditLog",
        ),
    ]
