# Generated by Django 5.2.9 on 2026-02-01 10:00
# CascadeEventArchive is_test 필드 및 복합 인덱스 추가

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    CascadeEventArchive 테이블에 is_test 필드 및 복합 인덱스 추가.

    추가 내용:
    - is_test: BooleanField (테스트 환경 이벤트 여부)
    - idx_cascade_test_ts: 복합 인덱스 (is_test, -timestamp)
    """

    dependencies = [
        ("shopping", "0032_add_postmortem_record"),
    ]

    operations = [
        # selfhealing_cascade_events 테이블에 is_test 필드 추가
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    -- is_test 컬럼이 없으면 추가
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'selfhealing_cascade_events'
                        AND column_name = 'is_test'
                    ) THEN
                        ALTER TABLE selfhealing_cascade_events
                        ADD COLUMN is_test BOOLEAN NOT NULL DEFAULT FALSE;

                        -- 개별 인덱스 생성
                        CREATE INDEX IF NOT EXISTS idx_cascade_is_test
                        ON selfhealing_cascade_events (is_test);

                        -- 복합 인덱스 생성 (is_test, timestamp DESC)
                        CREATE INDEX IF NOT EXISTS idx_cascade_test_ts
                        ON selfhealing_cascade_events (is_test, timestamp DESC);

                        RAISE NOTICE 'Added is_test column and indexes to selfhealing_cascade_events';
                    ELSE
                        RAISE NOTICE 'is_test column already exists in selfhealing_cascade_events';
                    END IF;
                END $$;
            """,
            reverse_sql="""
                DO $$
                BEGIN
                    -- 인덱스 제거
                    DROP INDEX IF EXISTS idx_cascade_test_ts;
                    DROP INDEX IF EXISTS idx_cascade_is_test;

                    -- 컬럼 제거
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'selfhealing_cascade_events'
                        AND column_name = 'is_test'
                    ) THEN
                        ALTER TABLE selfhealing_cascade_events
                        DROP COLUMN is_test;

                        RAISE NOTICE 'Removed is_test column from selfhealing_cascade_events';
                    END IF;
                END $$;
            """,
        ),
    ]
