# Generated by Django 5.2.8 on 2026-09-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0034_drop_orphaned_selfhealing_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhookevent",
            name="event_id",
            field=models.CharField(
                db_index=True, help_text="웹훅 식별자 (toss:{orderId}:{status})", max_length=200, verbose_name="이벤트 ID"
            ),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="event_type",
            field=models.CharField(
                help_text="토스 결제 상태: DONE, CANCELED, ABORTED, EXPIRED", max_length=50, verbose_name="이벤트 타입"
            ),
        ),
    ]
