# Generated by Django 5.2.8 on 2026-09-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0035_webhookevent_toss_status_vocabulary"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="toss_secret",
            field=models.CharField(blank=True, max_length=50, verbose_name="토스 웹훅 검증값"),
        ),
        migrations.AddField(
            model_name="payment",
            name="virtual_account_bank_code",
            field=models.CharField(blank=True, max_length=20, verbose_name="가상계좌 은행코드"),
        ),
        migrations.AddField(
            model_name="payment",
            name="virtual_account_due_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="입금 기한"),
        ),
        migrations.AddField(
            model_name="payment",
            name="virtual_account_number",
            field=models.CharField(blank=True, max_length=50, verbose_name="가상계좌 번호"),
        ),
    ]
