# Generated by Django 5.2.8 on 2026-09-23 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0036_payment_virtual_account_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="shopping.cart",
                verbose_name="주문 장바구니",
            ),
        ),
    ]
