# Generated by Django 5.2.8 on 2026-09-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0037_order_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillog",
            name="failed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="재발송 스윕이 진행 중인 재시도와 겹치지 않도록 기다리는 기준",
                null=True,
                verbose_name="마지막 실패 일시",
            ),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="resend_count",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="retry_failed_emails_task 가 다시 보낸 횟수", verbose_name="재발송 횟수"
            ),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="task_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name="발송 태스크 ID"),
        ),
        migrations.AddConstraint(
            model_name="pointhistory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("type", "earn")), fields=("order",), name="unique_earn_per_order"
            ),
        ),
    ]
